name: Debug Only (Temporary)

on:
  workflow_dispatch:      # Manual button ke liye

jobs:
  debug-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests pycryptodome

      - name: Run Debug Script
        env:
          # --- YAHAN MAINE NAAM SAHI KIYE HAIN ---
          # Left Side = Script mein jo naam chahiye
          # Right Side = Aapke GitHub Secrets ka asli naam
          BASE_URL: ${{ secrets.CRICIFY_URL }}
          KEY_HEX: ${{ secrets.CRICIFY_KEY }}
          IV_HEX: ${{ secrets.CRICIFY_IV }}
          KEY_HEX_2: ${{ secrets.CRICIFY_KEY_2 }}
          IV_HEX_2: ${{ secrets.CRICIFY_IV_2 }}
        run: python debug_match.py
