name: Update Cricify Links

on:
  schedule:
    - cron: '0 */1 * * *' # Har 1 ghante mein chalega
  workflow_dispatch:      # Manual run button

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pycryptodome requests

      - name: Run decryption script
        run: python decrypt_cricify.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # YAHAN CHANGE HAI: .json ki jagah wapas .m3u kar diya hai
          git add playlist.m3u
          
          git commit -m "Auto-update cricket M3U with Headers & DRM" || exit 0
          git push
