name: Update Cricify Links

on:
  schedule:
    - cron: '0 */1 * * *' # Every 1 Hour
  workflow_dispatch:      # Manual Button

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pycryptodome requests

      - name: Run script (ripalc.py)
        env:
          # Secrets mapping
          BASE_URL: ${{ secrets.CRICIFY_URL }}
          KEY_HEX: ${{ secrets.CRICIFY_KEY }}
          IV_HEX: ${{ secrets.CRICIFY_IV }}
          KEY_HEX_2: ${{ secrets.CRICIFY_KEY_2 }} # Backup Key
          IV_HEX_2: ${{ secrets.CRICIFY_IV_2 }}   # Backup IV
        # YAHAN NAME CHANGE HUAA HAI
        run: python ripalc.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.m3u
          git commit -m "Auto-update playlist via ripalc.py" || exit 0
          git push
