name: Update Ripalc Playlist

on:
  schedule:
    - cron: '*/15 * * * *' # Har 1 ghante mein chalega
  workflow_dispatch:      # Manual run button

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pycryptodome requests

      - name: Run script (ripalc.py)
        # ðŸ‘‡ Sirf ye secrets section update kiya hai
        env:
          CRIC_BASE_URL: ${{ secrets.CRIC_BASE_URL }}
          CRIC_KEY_1: ${{ secrets.CRIC_KEY_1 }}
          CRIC_IV_1: ${{ secrets.CRIC_IV_1 }}
          CRIC_KEY_2: ${{ secrets.CRIC_KEY_2 }}
          CRIC_IV_2: ${{ secrets.CRIC_IV_2 }}
        run: python ripalc.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.m3u
          git commit -m "Update playlist using ripalc" || exit 0
          git push
